const CATS={musica:['♪','Música'],dj_ball:['◌','DJ / ball'],cultura_popular:['✺','Cultura popular'],infantil:['☻','Infantil'],tallers:['✎','Tallers / activitats'],gastronomia:['◇','Gastronomia'],espectacles:['◈','Espectacles'],altres:['·','Altres']};
const DAYS=['2026-08-14','2026-08-15','2026-08-16','2026-08-17','2026-08-18','2026-08-19','2026-08-20','2026-08-21'],WEEK=['dg','dl','dt','dc','dj','dv','ds'];
let activities=[],selectedDate=defaultDate(),view='now',category='all',tab='today',query='',saved=new Set(JSON.parse(localStorage.getItem('festigracia-saved')||'[]')),nearMode=false,deferredPrompt=null;
const $=s=>document.querySelector(s),list=$('#eventList'),status=$('#status');
function defaultDate(){const d=new Date(),iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;return DAYS.includes(iso)?iso:DAYS[0]}
function minutes(t){const [h,m]=t.split(':').map(Number);return h*60+m} function nowMins(){const d=new Date();return d.getHours()*60+d.getMinutes()}
function niceDate(iso){const d=new Date(iso+'T12:00:00');return `${WEEK[d.getDay()]}. ${d.getDate()}`}
function renderDays(){const nav=$('#dateNav');nav.innerHTML='';DAYS.forEach(d=>{const dt=new Date(d+'T12:00'),b=document.createElement('button');b.className='day-btn'+(d===selectedDate?' active':'');b.innerHTML=`<strong>${dt.getDate()}</strong><span>${WEEK[dt.getDay()]}</span>`;b.onclick=()=>{selectedDate=d;nearMode=false;$('#nearBtn').classList.remove('active');renderDays();render()};nav.appendChild(b)});nav.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'})}
function renderFilters(){const box=$('#filters');box.innerHTML='';[['all',['','Totes']],...Object.entries(CATS)].forEach(([key,v])=>{const b=document.createElement('button');b.className='filter-btn'+(category===key?' active':'');b.textContent=(v[0]?v[0]+' ':'')+v[1];b.onclick=()=>{category=key;renderFilters();render()};box.appendChild(b)})}
function displayName(c){return CATS[c]?.[1]||'Altres'} function mapUrl(loc){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(loc+', Gràcia, Barcelona')}`}
function effectiveWindow(e){let s=minutes(e.start),en=e.end?minutes(e.end):s+45;if(e.end&&en<s)en+=1440;return[s,en]}
function currentMatch(e){let n=nowMins();if(e.lateNight&&n<300)n+=1440;let[s,en]=effectiveWindow(e);if(e.lateNight)s+=1440;return n>=s-15&&n<=en}
function upcomingMatch(e){let n=nowMins();if(e.lateNight&&n<300)n+=1440;let s=minutes(e.start)+(e.lateNight?1440:0);return s>n&&s<=n+120}
function baseFiltered(){let a=activities.filter(e=>e.date===selectedDate);if(category!=='all')a=a.filter(e=>e.category===category);if(query){const q=query.toLowerCase();a=a.filter(e=>(e.title+' '+e.location).toLowerCase().includes(q))}if(tab==='saved')a=a.filter(e=>saved.has(e.id));return a}
function sortEvents(a){return [...a].sort((x,y)=>nearMode&&x._distance!=null&&y._distance!=null?x._distance-y._distance:(minutes(x.start)+(x.lateNight?1440:0))-(minutes(y.start)+(y.lateNight?1440:0)))}
function eventCard(e){const n=$('#eventTemplate').content.firstElementChild.cloneNode(true);n.querySelector('.event-time').textContent=e.start;n.querySelector('.event-end').textContent=e.end?`— ${e.end}`:'';n.querySelector('.event-title').textContent=e.title;n.querySelector('.event-location').textContent=e.location;n.querySelector('.category-pill').textContent=displayName(e.category);n.querySelector('.recurring-mark').hidden=!e.recurring;const m=n.querySelector('.map-link');m.href=mapUrl(e.location);if(e._distance!=null)n.querySelector('.distance').textContent=e._distance<1000?`${Math.round(e._distance/10)*10} m`:`${(e._distance/1000).toFixed(1)} km`;const s=n.querySelector('.save-btn');s.textContent=saved.has(e.id)?'♥':'♡';s.classList.toggle('saved',saved.has(e.id));s.onclick=()=>{saved.has(e.id)?saved.delete(e.id):saved.add(e.id);localStorage.setItem('festigracia-saved',JSON.stringify([...saved]));updateSaved();render()};return n}
function addSection(title,a){if(!a.length)return;const h=document.createElement('div');h.className='section-label';h.textContent=title;list.appendChild(h);sortEvents(a).forEach(e=>list.appendChild(eventCard(e)))}
function render(){list.innerHTML='';const a=baseFiltered(),isToday=selectedDate===defaultDate();$('#heroTitle').textContent=tab==='saved'?'El teu programa, sense soroll.':isToday?'Què pots fer ara mateix?':`Plans per ${niceDate(selectedDate)}.`;if(tab==='saved')addSection('El meu pla',a);else if(view==='now'&&isToday){const cur=a.filter(currentMatch),up=a.filter(e=>!cur.includes(e)&&upcomingMatch(e));addSection('Ara',cur);addSection('A continuació · 2 h',up);if(!cur.length&&!up.length)list.innerHTML='<div class="empty"><strong>Cap activitat en aquesta franja.</strong>Prova “Tot el dia” o canvia de categoria.</div>'}else{addSection(nearMode?'Més a prop':'Programa',a);if(!a.length)list.innerHTML='<div class="empty"><strong>No hi ha coincidències.</strong>Canvia els filtres o la cerca.</div>'}status.textContent=nearMode?'Mode proximitat actiu. Les distàncies es calculen al teu navegador.':`${a.length} activitats en aquesta selecció`;updateSaved()}
function updateSaved(){$('#savedCount').textContent=saved.size||''}
function hav(a,b,c,d){const R=6371000,r=x=>x*Math.PI/180,dp=r(c-a),dl=r(d-b),q=Math.sin(dp/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
async function geocode(loc){const k='fg-geo-'+loc,c=localStorage.getItem(k);if(c)return JSON.parse(c);const u='https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=es&q='+encodeURIComponent(loc+', Gràcia, Barcelona');const r=await fetch(u,{headers:{'Accept-Language':'ca'}});if(!r.ok)throw 0;const j=await r.json(),v=j[0]?{lat:+j[0].lat,lon:+j[0].lon}:null;if(v)localStorage.setItem(k,JSON.stringify(v));return v}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function nearMe(){if(!navigator.geolocation){status.textContent='Aquest navegador no permet geolocalització.';return}status.textContent='Demanant la teva ubicació…';navigator.geolocation.getCurrentPosition(async p=>{nearMode=true;$('#nearBtn').classList.add('active');view='all';document.querySelectorAll('.seg').forEach(x=>x.classList.toggle('active',x.dataset.view==='all'));const visible=baseFiltered().filter(e=>!['Itinerante','Tota la Vila','Diversos carrers','Activitats diverses','Espais veïnals'].includes(e.location)),locs=[...new Set(visible.map(e=>e.location))];status.textContent=`Calculant proximitat per ${locs.length} ubicacions…`;for(let i=0;i<locs.length;i++){try{const g=await geocode(locs[i]);if(g)activities.filter(e=>e.location===locs[i]).forEach(e=>e._distance=hav(p.coords.latitude,p.coords.longitude,g.lat,g.lon))}catch{}if(i<locs.length-1)await sleep(1050)}render()},()=>status.textContent='No s’ha pogut obtenir la ubicació. Revisa els permisos del navegador.',{timeout:10000,maximumAge:300000})}
async function boot(){activities=await fetch('activities.json').then(r=>r.json());renderDays();renderFilters();updateSaved();render();$('#searchInput').oninput=e=>{query=e.target.value.trim();render()};document.querySelectorAll('.seg').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('.seg').forEach(x=>x.classList.toggle('active',x===b));render()});$('#nearBtn').onclick=nearMe;document.querySelectorAll('.bottom').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('.bottom').forEach(x=>x.classList.toggle('active',x===b));if(tab==='today'){selectedDate=defaultDate();view='now';query='';$('#searchInput').value='';document.querySelectorAll('.seg').forEach(x=>x.classList.toggle('active',x.dataset.view==='now'));renderDays()}else if(tab==='explore'){view='all';document.querySelectorAll('.seg').forEach(x=>x.classList.toggle('active',x.dataset.view==='all'));$('#searchInput').focus()}render()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};boot().catch(()=>{list.innerHTML='<div class="empty"><strong>No s’han pogut carregar les dades.</strong>Recarrega la pàgina.</div>'});